/**
 * Next Steps Card — Displays mode-adapted recommended actions
 * Adapts to user-selected deviation mode (Strict/Flexible/Exploratory/Free)
 */

import React from 'react';

interface NextStep {
  priority: 'P0' | 'P1' | 'P2';
  action: string;
}

interface NextStepsProps {
  mode: 'strict' | 'flexible' | 'exploratory' | 'free';
  steps: NextStep[];
}

export const NextStepsCard: React.FC<NextStepsProps> = ({ mode, steps }) => {
  const getModeEmoji = () => {
    switch (mode) {
      case 'strict': return '🔴';
      case 'flexible': return '🟡';
      case 'exploratory': return '🟢';
      case 'free': return '⚪';
      default: return '🎯';
    }
  };

  const getModeLabel = () => {
    switch (mode) {
      case 'strict': return 'Strict Mode (0%)';
      case 'flexible': return 'Flexible Mode (25%)';
      case 'exploratory': return 'Exploratory Mode (50%)';
      case 'free': return 'Free Mode (100%)';
      default: return 'Unknown Mode';
    }
  };

  const getModeDescription = () => {
    switch (mode) {
      case 'strict':
        return 'Focus ONLY on P0 tasks from baseline plan. Reject ALL new ideas.';
      case 'flexible':
        return 'Focus on P0+P1 tasks. New ideas OK if total bias < 25%.';
      case 'exploratory':
        return 'Welcome creative ideas. New features OK if total bias < 50%.';
      case 'free':
        return 'Creative mode. All ideas welcome. No constraints.';
      default:
        return '';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'P0': return '#ff4d4d';
      case 'P1': return '#ff9500';
      case 'P2': return '#667eea';
      default: return '#666';
    }
  };

  return (
    <div className="kpi-card next-steps-card">
      <div className="kpi-header">
        <h3>🎯 Next Steps</h3>
        <div className="tooltip">
          <span className="tooltip-icon">ℹ️</span>
          <div className="tooltip-content">
            <strong>Mode-Driven Recommendations:</strong><br/>
            Actions adapt to your selected Perception Angle.<br/><br/>
            <strong>Strict (0%):</strong> P0 only, reject new ideas<br/>
            <strong>Flexible (25%):</strong> P0+P1, new ideas if bias &lt; 25%<br/>
            <strong>Exploratory (50%):</strong> Creative ideas welcome<br/>
            <strong>Free (100%):</strong> No constraints<br/><br/>
            Generated by LLM based on current Plan, Tasks, and Bias.
          </div>
        </div>
      </div>

      <div className="kpi-mode-indicator">
        <span className="mode-emoji">{getModeEmoji()}</span>
        <span className="mode-label">{getModeLabel()}</span>
      </div>
      
      <p className="mode-description">{getModeDescription()}</p>

      <div className="kpi-steps">
        {steps.length > 0 ? (
          <ol className="steps-list">
            {steps.map((step, index) => (
              <li key={index} className="step-item">
                <span 
                  className="step-priority" 
                  style={{ color: getPriorityColor(step.priority) }}
                >
                  [{step.priority}]
                </span>
                <span className="step-action">{step.action}</span>
              </li>
            ))}
          </ol>
        ) : (
          <p className="no-steps">✅ No actions required. All on track!</p>
        )}
      </div>
    </div>
  );
};

