#!/bin/bash

echo "═══════════════════════════════════════════════════════════════"
echo "🧠  RL3 REPL - TEST SCRIPT"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📋 Tests disponibles:"
echo ""
echo "1. Test direct REPL:"
echo "   node .reasoning/repl.js"
echo ""
echo "2. Test via rl3 binary:"
echo "   ./rl3"
echo "   ./rl3 shell"
echo "   ./rl3 chat"
echo ""
echo "3. Commandes à tester dans le REPL:"
echo "   > help"
echo "   > context"
echo "   > history"
echo "   > Où en est le système ?"
echo "   > Quelles sont les prochaines tâches ?"
echo "   > Analyse AUTOBIOGRAPHIE_VOLUME_I.md"
echo "   > Montre-moi les patterns"
echo "   > Liste les ADRs"
echo "   > exit"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "💡 Pour tester maintenant:"
echo "   chmod +x test-repl.sh"
echo "   ./test-repl.sh"
echo ""
echo "   Puis lancez: ./rl3"
echo ""
echo "═══════════════════════════════════════════════════════════════"

