/**
 * RBOM Types - Architectural Decision Records (ADRs)
 * 
 * Structure pour gérer les décisions architecturales avec preuves liées
 */

export interface ADR {
    id: string;                    // UUID unique
    title: string;                  // Titre de la décision
    status: 'proposed' | 'accepted' | 'deprecated' | 'superseded';
    createdAt: string;              // ISO 8601
    modifiedAt: string;             // ISO 8601
    author: string;                 // Nom de l'auteur
    
    // Contenu de l'ADR
    context: string;                 // Contexte de la décision
    decision: string;                // Décision prise
    consequences: string;           // Conséquences
    
    // Métadonnées
    tags: string[];                 // Tags pour catégorisation
    components: string[];           // Composants concernés
    relatedADRs: string[];         // IDs des ADRs liés
    
    // Liens avec les preuves (Evidence nodes)
    evidenceIds: string[];          // IDs des Evidence qui prouvent cette décision
    
    // Génération automatique
    lastSyncedAt?: string;          // Dernière synchronisation avec Evidence
    autoGenerated: boolean;          // Généré automatiquement ou manuellement
}

export interface ADREvidenceLink {
    adrId: string;
    evidenceId: string;
    relationship: 'supports' | 'contradicts' | 'references';
    createdAt: string;
}

export interface ADRSearchFilter {
    status?: ADR['status'];
    tags?: string[];
    components?: string[];
    author?: string;
    dateRange?: { start: string; end: string };
}

// ✅ Statut de l'ADR pour le filtering
export type ADRStatus = ADR['status'];

