/**
 * RBOM Types - Architectural Decision Records (ADRs)
 * 
 * Structure pour gérer les décisions architecturales avec preuves liées
 */

export interface ADREnhanced {
    id: string;                    // UUID unique
    title: string;                  // Titre de la décision
    status: 'proposed' | 'accepted' | 'deprecated' | 'superseded';
    createdAt: string;              // ISO 8601
    modifiedAt: string;             // ISO 8601
    author: string;                 // Nom de l'auteur
    
    // Contenu de l'ADR
    context: string;                 // Contexte de la décision
    decision: string;                // Décision prise
    consequences: string;           // Conséquences
    
    // Métadonnées
    tags: string[];                 // Tags pour catégorisation
    components: string[];           // Composants concernés
    relatedADRs: string[];         // IDs des ADRs liés
    
    // Liens avec les preuves (Evidence nodes)
    evidenceIds: string[];          // IDs des Evidence qui prouvent cette décision
    
    // Génération automatique
    lastSyncedAt?: string;          // Dernière synchronisation avec Evidence
    autoGenerated: boolean;          // Généré automatiquement ou manuellement
    
    // Enhanced fields (Phase 2)
    tradeoffs?: {
        pros: string[];             // Avantages de la décision
        cons: string[];             // Inconvénients de la décision
    };
    rejectedOptions?: {
        option: string;             // Alternative rejetée
        reason: string;             // Raison du rejet
    }[];
    assumptions?: string[];          // Hypothèses sous-jacentes
    constraints?: {
        technical?: string[];       // Contraintes techniques
        business?: string[];        // Contraintes business
        timeline?: string;          // Contrainte de timing
    };
    risks?: {
        risk: string;               // Description du risque
        probability: 'low' | 'medium' | 'high';
        impact: 'low' | 'medium' | 'high';
        mitigation?: string;        // Mesure de mitigation
    }[];
    mitigations?: string[];          // Mesures globales de mitigation
    supersededBy?: string;          // ID de l'ADR qui remplace celui-ci
    supersedes?: string[];          // IDs des ADRs remplacés par celui-ci
}

// Keep backward compatibility
export interface ADR extends ADREnhanced {}

export interface ADREvidenceLink {
    adrId: string;
    evidenceId: string;
    relationship: 'supports' | 'contradicts' | 'references';
    createdAt: string;
}

export interface ADRSearchFilter {
    status?: ADR['status'];
    tags?: string[];
    components?: string[];
    author?: string;
    dateRange?: { start: string; end: string };
}

// ✅ Statut de l'ADR pour le filtering
export type ADRStatus = ADR['status'];

